### ISSUE TITLE
feat: show boards and articles

### ISSUE THREAD

**Issue by kkyueing** [OHHAKO/react-app#12]
The site should show a list of boards, and each board, in turn, should show a list of articles.

The structure would be like the following:

```jsx
<App>
  <BoardList>
    <Board>
      <ArticleList>
        <ArticleRow />
        <ArticleRow />
        ...
       </ArticleList>
     </Board>
    <Board>
    ...
    </Board>
  </BoardList>
</App>
```

**Comment by OHHAKO** [comment]
are those tags were made by you or be assigned from bootstrap/ jxs?

**Comment by kkyueing** [comment]
I haven't made them yet. The code above is just a proposal. If you think the proposal is okay, I'll create a PR implementing those components.

**Comment by kkyueing** [comment]
I've just learnt that it is conventional to send an incomplete PR to encourage discussions between developers. So I've sent the PR #15 which contains a code implements the idea suggested in this issue.

Please just take a look at it and let me know your thought. 😄
